mod genetic;
mod snake;

use console_engine::{pixel, Color, ConsoleEngine, KeyCode};
use genetic::{
    population::Population,
    traits::{HasFitness, HasLife, HasTimePerception},
};
use rand::{thread_rng, Rng};
use rand_distr::{Distribution, Normal};
use rayon::prelude::*;
use snake::{Snake, FIELD_HEIGHT, FIELD_WIDTH};
use std::sync::{Arc, Mutex};

fn draw_borders(canvas: &mut ConsoleEngine, shift: (i32, i32)) {
    let border_color = Color::DarkRed;
    let border_pixel = pixel::pxl_bg(' ', border_color);

    canvas.set_pxl(shift.0, shift.1, border_pixel);
    canvas.set_pxl((FIELD_WIDTH + 1) as i32 + shift.0, shift.1, border_pixel);
    canvas.set_pxl(
        (FIELD_WIDTH + 1) as i32 + shift.0,
        (FIELD_HEIGHT + 1) as i32 + shift.1,
        border_pixel,
    );
    canvas.set_pxl(shift.0, (FIELD_HEIGHT + 1) as i32 + shift.1, border_pixel);

    for x in 0..FIELD_WIDTH + 1 {
        canvas.set_pxl(x as i32 + shift.0, shift.1, border_pixel);
        canvas.set_pxl(
            x as i32 + shift.0,
            (FIELD_HEIGHT + 1) as i32 + shift.1,
            border_pixel,
        );
    }
    for y in 0..FIELD_HEIGHT + 1 {
        canvas.set_pxl(shift.0, y as i32 + shift.1, border_pixel);
        canvas.set_pxl(
            (FIELD_WIDTH + 1) as i32 + shift.0,
            y as i32 + shift.1,
            border_pixel,
        );
    }
}

/**
 * I admit, this function was generated by ChatGPT.
 * Unfortunately, it returns a number in the range [n, m], not [n, m) as one might reasonably expect.
 */
fn generate_random_number_tending_towards_smaller(n: u32, m: u32, small_likelihood: f64) -> u32 {
    let mean = (n + m) / 2;
    let std_dev = (m - n) / 4;
    let normal = Normal::new(mean as f64, std_dev as f64).unwrap();

    let mut rng = thread_rng();
    let mut num;
    loop {
        num = normal.sample(&mut rng) as u32;
        if num >= n && num <= m {
            break;
        }
    }

    let rand_num = rng.gen_range(0.0..1.0);
    if rand_num <= small_likelihood {
        n + rng.gen_range(0..(num - n).max(1))
    } else {
        num + rng.gen_range(0..(m - num + 1).max(1))
    }
}

fn main() {
    let mut population: Population<Snake> = Population::new(2000);

    let status_bar_height = 8;
    let mut engine = ConsoleEngine::init(
        (FIELD_WIDTH + 4 + 60).into(),
        (FIELD_HEIGHT + 4 + status_bar_height).into(),
        300,
    )
    .unwrap();

    let mut draw = true;

    loop {
        engine.wait_frame();
        engine.clear_screen();

        let shift = (0, status_bar_height as i32);

        if draw {
            draw_borders(&mut engine, shift);
        }

        population.tick();

        if population.is_dead() {
            population.evolution();
        }

        for snake in &mut population.get_genomes().iter() {
            if !snake.is_alive() {
                continue;
            }

            if draw {
                engine.set_pxl(
                    snake.get_apple().current.0 + 1 + shift.0,
                    snake.get_apple().current.1 + 1 + shift.1,
                    pixel::pxl_bg(' ', Color::Red),
                );
                for cell in snake.get_cells() {
                    engine.set_pxl(
                        cell.current.0 + 1 + shift.0,
                        cell.current.1 + 1 + shift.1,
                        pixel::pxl_bg(' ', Color::Green),
                    );
                }
            }
        }

        engine.print(
            1,
            0,
            format!(
                "snakes_alive: {}",
                *population.alive_genomes_count.lock().unwrap(),
            )
            .as_str(),
        );

        engine.print(
            1,
            1,
            format!("generation: {}", population.generation,).as_str(),
        );
        engine.print(
            1,
            2,
            format!("mutation_rate: {}", population.mutation_rate).as_str(),
        );
        engine.print(
            1,
            3,
            format!(
                "max_fitness_current: {}",
                *population.max_fitness_current.lock().unwrap()
            )
            .as_str(),
        );
        engine.print(
            1,
            4,
            format!("max_fitness_prev: {}", population.max_fitness_prev).as_str(),
        );

        if engine.is_key_pressed(KeyCode::Char(' ')) {
            draw = !draw;
        }

        if engine.is_key_pressed(KeyCode::Esc) {
            break;
        }

        if engine.is_key_pressed(KeyCode::Char('q')) {
            population.kill();
        }

        engine.draw();
    }
}
